# Generated by Django 5.0.7 on 2024-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chats",
            options={"verbose_name_plural": "chats"},
        ),
        migrations.AlterModelOptions(
            name="chatsmembers",
            options={"verbose_name_plural": "chats members"},
        ),
    ]
