# Generated by Django 5.0.7 on 2024-10-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
