# Generated by Django 5.0.7 on 2024-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
