# Generated by Django 5.0.7 on 2024-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_user_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img_url",
            field=models.URLField(
                blank=True, default="https://i.ibb.co/N1kFxGn/user.png", null=True
            ),
        ),
    ]
